### ISSUE TITLE
Hover Transition effect on products.

### ISSUE THREAD

**Issue by Aarav238** [KiranAminPanjwani/LeatherHoard#121]
### 🎇 Description

I want to add transition effect  on hovering on product , this will give a great experience to the users. I want to add this feature in the attached screenshot.

### 🖼 Screenshots

![before](https://user-images.githubusercontent.com/95538627/194875595-204e43fc-b3e1-41db-b219-2aad8ad98aad.png)

**Comment by abitsalihu** [comment]
Hey, I would like to work on this issue. :)

**Comment by Aarav238** [comment]
As i Have raised this Please Assign this to me. I can do it in an hour.

**Comment by KiranAminPanjwani** [comment]
@Aarav238 Sure, go ahead!😊

**Comment by Aditya-Harsh** [comment]
Hi there,
I have experience working in web development domain and would love to work on this issue.
Please assign it to me.
