### ISSUE TITLE
Social media links are not working

### ISSUE THREAD

**Issue by SaiSantosh2209** [KiranAminPanjwani/LeatherHoard#124]
### 🎇 Description

* I was going through your website and I found that your social media handles were not working  in the "Contact Us" section . 
* I will attach all of your social media handle links so that it will be accessible for the others who will be viewing your website.

### 🖼 Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/83724995/194913141-f8f85eaf-d5e9-405b-be9a-0975ee2a2cc1.png)

**Comment by KiranAminPanjwani** [comment]
But there are no such socials handles for this page.

**Comment by SaiSantosh2209** [comment]
I can add default links if you want.

**Comment by Aditya-Harsh** [comment]
Hi there,
I have experience working in web development domain and would love to work on this issue.
Please assign it to me.

**Comment by KiranAminPanjwani** [comment]
> I can add default links if you want.

Currently, that modification is not necessary.
