### ISSUE TITLE
Replace top text in the button with an arrow 

### ISSUE THREAD

**Issue by SaiSantosh2209** [KiranAminPanjwani/LeatherHoard#126]
### 🎇 Description

*  I would like to replace the top icon  with the arrow icon so that it will be more understandable for the user to use this particular feature

### 🖼 Screenshots

![Screenshot (4)](https://user-images.githubusercontent.com/83724995/194920834-372a8076-701a-4015-98cc-73f919e0795d.png)

**Comment by abitsalihu** [comment]
Hey, I would like to work on this issue. :)

**Comment by KiranAminPanjwani** [comment]
I'm sorry, I don't want to make these changes. Kindly try to find other bugs/issues. For example: Try ti fix sign-in/sign-up form.
