### ISSUE TITLE
Create Counter on About Us Page

### ISSUE THREAD

**Issue by Mahak008** [KiranAminPanjwani/LeatherHoard#130]
### 🎇 Description

As 1000+ million sales is written, on loading the page it will count and increase from 0 to 1000.

**Comment by Mahak008** [comment]
Kindly assign this issue to me @KiranAminPanjwani

**Comment by KiranAminPanjwani** [comment]
@Mahak008 Please go ahead! 😊

**Comment by manishgupta416** [comment]
Can you assign to me?
