### ISSUE TITLE
Social media icons on the footer section can be enhanced

### ISSUE THREAD

**Issue by SreenikaMyakala** [KiranAminPanjwani/LeatherHoard#131]
### 🎇 Description

If approved then please assign this task to me i will work on it

**Comment by pranavhole** [comment]
Hey, I want to work on this issue can you assign this to me?

**Comment by KiranAminPanjwani** [comment]
Kindly provide a brief description or reference screenshots for the changes you want to make.😊

**Comment by SreenikaMyakala** [comment]
I think someone already added the effects, i wanted to add rounded social media icons and hover effect to them
