### ISSUE TITLE
[FEATURE] Responsive FAQ Page in Accordion dropdown format

### ISSUE THREAD

**Issue by yashjoshi-dotcom** [KiranAminPanjwani/LeatherHoard#132]
### 🎇 Description

I just noticed that the FAQ link on the footer of the website is not working. I would like to add an FAQ page in a collapsible format with the theme similar to that of the whole website. I can do this with plain HTML or bootstrap, whichever you deem suitable. 
A sample screenshot has been provided below for your reference.

### 🖼 Screenshots

![image](https://user-images.githubusercontent.com/77540753/195105847-dcee4898-1d90-4abc-8e97-4e85a7c573c4.png)

**Comment by pranavhole** [comment]
Hey, I want to work on this issue For the hacktoberfest, Can you assign this to me?

**Comment by yashjoshi-dotcom** [comment]
Closed due to lack of comments from the repo owner
