### ISSUE TITLE
Redesigning the Login page 

### ISSUE THREAD

**Issue by amitanshusahu** [KiranAminPanjwani/LeatherHoard#133]
### there is no use of a nav bar or a buy now button in the login page 
the user has come to register/login so no use of a by now or the nav ..
![image](https://user-images.githubusercontent.com/83657737/195115775-2049b0c6-d17e-4ab4-9d2f-7704dc680c69.png)

**Comment by amitanshusahu** [comment]
@KiranAminPanjwani  i would like to work on this

**Comment by KiranAminPanjwani** [comment]
How will the user go back to the home page then?

**Comment by amitanshusahu** [comment]
> How will the user go back to the home page then? I would suggest keeping the "Home" nav link and removing others if you want to.

@KiranAminPanjwani , you are correct, but if we consider some of the major website like **amazone** or say **google**, there we are taken to a login page, after providing  correct credentials when we click the **login button** the site **automatically redirects** to the **home** page.

 well that would be some **backend** work 😅 , but it can be done in the **frontend** also using **js**, and the credentials can be stored to the **local storage** to reflect the data to other pages as well 😊 . If for some reason the user decides not to login , at the end there could be a  __"Back to Home"__  link.. Hope it makes sence .. 😅  , but if you like the nav approach, Ok i will do that 👍🏻  

do share your thoughts on this..
