### ISSUE TITLE
Redesigning  PrivacyPolicy page

### ISSUE THREAD

**Issue by Arjundotadex** [KiranAminPanjwani/LeatherHoard#135]
### 🎇 Description

The privacy policy page is not up to the mark. ILL adds font size, color, type, indentation, and many more. I'll add more images and make a few more changes with the help of bootstrap(if allowed). If not allowed to use bootstrap then ill stick to the HTML itself.

**Comment by KhanyaMateta** [comment]
I would like to take this issue. Do you you have any specific designs that you would like me to implement?

**Comment by KiranAminPanjwani** [comment]
@Arjundotadex Bootstrap is a good idea. Try to use awesome images.

**Comment by Arjundotadex** [comment]
yes, I'll use bootstrap only
