### ISSUE TITLE
Feature Suggestion: Clicking on logo in footer links back to top of the page

### ISSUE THREAD

**Issue by terrifricker** [KiranAminPanjwani/LeatherHoard#16]
The LeatherHoard logo located in the upper left corner of the Footer section could be made a link back to the top of the page.

![Screen Shot 2022-09-29 at 1 37 51 PM](https://user-images.githubusercontent.com/51532684/193137478-b5162057-ca6f-4cd9-8462-e67098a90b7f.png)

The image could become a link element that when clicked does one of two things:
1. Reloads the page using href="https://leatherhoard.netlify.app/index.html".
2. Jumps back to header by adding an id="top" (or similar term) and using href="#top".

I prefer the second idea.

**Comment by KiranAminPanjwani** [comment]
> The LeatherHoard logo located in the upper left corner of the Footer section could be made a link back to the top of the page.
> 
> ![Screen Shot 2022-09-29 at 1 37 51 PM](https://user-images.githubusercontent.com/51532684/193137478-b5162057-ca6f-4cd9-8462-e67098a90b7f.png)
> 
> The image could become a link element that when clicked does one of two things:
> 
> 1. Reloads the page using href="https://leatherhoard.netlify.app/index.html".
> 2. Jumps back to header by adding an id="top" (or similar term) and using href="#top".
> 
> I prefer the second idea.

Thank you for highlighting this, please go ahead! 🤩
