### ISSUE TITLE
Improvement in the search bar

### ISSUE THREAD

**Issue by himadeepthi1** [KiranAminPanjwani/LeatherHoard#165]
### 🎇 Description

Website would look more nice , if instead of  a search icon alone  if  there is search bar with some placeholders 

### 🖼 Screenshots

![searchbar](https://github.com/KiranAminPanjwani/LeatherHoard/assets/133694562/0333abf2-9ca3-4ca7-a932-e59f5069fdf7)

**Comment by himadeepthi1** [comment]
@KiranAminPanjwani please review this and assign this issue to me , so that I can proceed further

**Comment by KiranAminPanjwani** [comment]
Sure, please go ahead.✨

**Comment by himadeepthi1** [comment]
@KiranAminPanjwani I have opened a pr regarding #166 , please verify and merge the pr
