### ISSUE TITLE
Sections not updating!

### ISSUE THREAD

**Issue by Janhvi52** [KiranAminPanjwani/LeatherHoard#20]
![2022-09-30 (2)](https://user-images.githubusercontent.com/97719669/193253215-a1ddff55-f646-4826-a844-1067ffa0cb58.png)

Upon clicking the about/product/contact/login options, we aren't directed to any new page it remains in the same page itself
Please assign me this issue @KiranAminPanjwani

**Comment by KiranAminPanjwani** [comment]
Kindly check, if the issue same issue is raised before. Try to find other bugs or add a new feature/section to the website.😊
