### ISSUE TITLE
Seperate product page or redirecting to collection section

### ISSUE THREAD

**Issue by amitanshusahu** [KiranAminPanjwani/LeatherHoard#21]
### the product page isn't available for the site
 when clicked on products (in the nav) the site can be taken to the collection section but it would be better to have a product page..

![image](https://user-images.githubusercontent.com/83657737/193259259-b4e48ecf-8b6b-485d-a6f6-c0f725f0ea5c.png)

**Comment by amitanshusahu** [comment]
### Request
i would like to work on this if you assign this to me... 😄 
given , it its open for the <i>#hacktoberfest2022</i>

**Comment by KiranAminPanjwani** [comment]
Yeah sure, please go ahead! 🤩
