### ISSUE TITLE
Make contact input fields more intuitive

### ISSUE THREAD

**Issue by rezwan2525** [KiranAminPanjwani/LeatherHoard#31]
When we focus on any of the input fields from the `Contact us` form, that field doesn't reflect the user's action. I think we should show box shadow around the input field, something like the below image - 
![focus-effect](https://user-images.githubusercontent.com/30120066/193383222-96cefb97-2794-4333-96b2-357417a8e37b.jpg)

Can I please include this in this project?

**Comment by KiranAminPanjwani** [comment]
Yeah sure, go ahead! 🤩
