### ISSUE TITLE
Designing needed in privacy policy page

### ISSUE THREAD

**Issue by samipak458** [KiranAminPanjwani/LeatherHoard#4]
I will change background and font color. Kindly assign me this issue.

**Comment by samipak458** [comment]
@KiranAminPanjwani

**Comment by sreejasaha19** [comment]
Hey, I want to contribute to this issue. Can I work on this issue? If yes, could you please assign it to me.

**Comment by KiranAminPanjwani** [comment]
> Hey, I want to contribute to this issue. Can I work on this issue? If yes, could you please assign it to me.

Please create a new issue and briefly define the changes you want to make. Thank you.☺
