### ISSUE TITLE
Enhance the design of the privacy policy page

### ISSUE THREAD

**Issue by kunaaal13** [KiranAminPanjwani/LeatherHoard#40]
The privacy policy page looks pretty basic now, I want to improve the design, please assign this to me under hacktoberfest label

**Comment by KiranAminPanjwani** [comment]
Sure, please go ahead!

**Comment by minhaj-313** [comment]
I want to Contribute in this Project for Hacktoberfest, If you Have any Issue then you can suggest me. I want to give my best
