### ISSUE TITLE
Scroll progress bar

### ISSUE THREAD

**Issue by kunaaal13** [KiranAminPanjwani/LeatherHoard#50]
**Description**
I want to add a scroll progress bar, it is generally seen in modern websites, would be a good edition to this website.

**Screenshots**
Like this scroll progress bar at the top
<img width="1438" alt="Screenshot 2022-10-01 at 9 44 18 PM" src="https://user-images.githubusercontent.com/84015751/193418443-577b2ccc-f837-4492-a8a0-1ab396b429c2.png">

**Comment by KiranAminPanjwani** [comment]
Go for it! 😊
Note: Maintain the theme of the website. Try to use the same hex codes that are being used on the website.

**Comment by kunaaal13** [comment]
Hey pls add hactoberfest accepted label pr issue no #50
