### ISSUE TITLE
Fixing products.html

### ISSUE THREAD

**Issue by logic-404** [KiranAminPanjwani/LeatherHoard#58]
### Description

Wrong popup is given when the like button inside products.html is pressed. Kindly assign me the issue so I can start working on it.

### Screenshots

https://user-images.githubusercontent.com/76689021/193427033-30571f1a-09ff-49d2-b025-080f75a884ed.mp4

**Comment by amitanshusahu** [comment]
## oops!! i missed it .. @logic-404  , my mistake..
if it gets assigned to you and if any help is required then then mention me in the comments, you can just console.log the e.traget and check for the childNodes .. and put this inside a " if " statement ...

### the overall logic would be like 👇🏻 
if (e.target.activeElement.childNode["some value"].src) { /* don't pass the src value */}

**Comment by KiranAminPanjwani** [comment]
@logic-404 Please go ahead! 🤩
