### ISSUE TITLE
Navbar buttons not functioning.

### ISSUE THREAD

**Issue by tushartalesara** [KiranAminPanjwani/LeatherHoard#6]
On clicking About, Products and Contact Us complete page reloads rather than this it should redirect to relevant section of the page.
Can you assign me this task as the part of hacktoberfest?

**Comment by saimaheshtaduri** [comment]
can I work on this. if this is open ? @KiranAminPanjwani

**Comment by KiranAminPanjwani** [comment]
> On clicking About, Products and Contact Us complete page reloads rather than this it should redirect to relevant section of the page. Can you assign me this task as the part of hacktoberfest?

Yeah sure, please go ahead! 🤩

**Comment by KiranAminPanjwani** [comment]
> can I work on this. if this is open ? @KiranAminPanjwani

Create a separate new issue so that I can assign it to you. Try to add a separate page for "Products", if possible. 😊

**Comment by aryaupadhyay24** [comment]
hello, I'm Arya Upadhyay I want to contribute on this issue
