### ISSUE TITLE
Contact button not working

### ISSUE THREAD

**Issue by AnshuPathak-88825** [KiranAminPanjwani/LeatherHoard#64]
### Description

https://user-images.githubusercontent.com/78332454/193448810-c102d009-60eb-424e-8db5-93fcecf67637.mp4

contact button should've link of contact section

**Comment by AnshuPathak-88825** [comment]
pls assign me this @KiranAminPanjwani

**Comment by KiranAminPanjwani** [comment]
Sure, please go ahead! 🤩

**Comment by AnshuPathak-88825** [comment]
Made pr for this issue pls review it and merge it
