### ISSUE TITLE
Exit cursor should be pointer

### ISSUE THREAD

**Issue by AnshuPathak-88825** [KiranAminPanjwani/LeatherHoard#66]
### Description

This exit icon should be cursor pointer

### Screenshots

![image](https://user-images.githubusercontent.com/78332454/193449323-a1e0d03a-6fd0-464b-b2c6-454bf1cde4d0.png)

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by KiranAminPanjwani** [comment]
Please go ahead! 🤩

**Comment by AnshuPathak-88825** [comment]
pls review my pull request then merge it
