### ISSUE TITLE
[Bug] Social icons should be consistent in all pages

### ISSUE THREAD

**Issue by rezwan2525** [KiranAminPanjwani/LeatherHoard#68]
### Description

**How to reproduce:**

1. Go to the footer section of the home page and hover over social icons
2. Go to the footer section of login page and hover over social icons
3. Observe they behave differently in the above step 1 and step 2

**Expected behavior:** The social icons should be consistent/same on all pages of the website.

**Actual behavior:** In the footer section, when we hover over social icons, we see two different behavior on the home page and  login page  

**Proposed design**: I think we can use the home page's social icons design on the login page as well. Please let me know your feedback on that.

### Screenshots

**Home page**
![home-page](https://user-images.githubusercontent.com/30120066/193450779-bddc2940-0b68-46da-98cc-763c72b78c99.jpg)

**Login page:**
![loginpage](https://user-images.githubusercontent.com/30120066/193450781-490622c6-07bb-46ab-a44a-175781cbdaa0.jpg)

**Comment by kritiag20** [comment]
@rezwan2525 I want to work on this issue.

**Comment by KiranAminPanjwani** [comment]
@rezwan2525 Please go ahead! 🤩
