### ISSUE TITLE
[Bug] Wrong menu selected in login page

### ISSUE THREAD

**Issue by rezwan2525** [KiranAminPanjwani/LeatherHoard#70]
### Description

Instead of the login menu selected, we can see 'Home' menu is active/selected on the login page. Can I please work on this?

### Screenshots

![image](https://user-images.githubusercontent.com/30120066/193452209-1a0098ee-e892-479a-b9ab-b40955825426.png)

**Comment by KiranAminPanjwani** [comment]
Sure, go ahead! 🤩
