### ISSUE TITLE
Contact Button is not working properly.

### ISSUE THREAD

**Issue by nihshesh** [KiranAminPanjwani/LeatherHoard#73]
### 🎇 Description

The contact button on the Home page is not directed towards the "Contact us" section. Can I work on this issue?

### 🖼 Screenshots

![issue hacktober](https://user-images.githubusercontent.com/61341935/193455854-e487c8e8-0df4-4a44-af7b-7c3fa2c15f92.PNG)

**Comment by KiranAminPanjwani** [comment]
Kindly check, if the issue same issue is raised before. Try to find other bugs or add a new feature/section to the website.😊
