### ISSUE TITLE
[FEATURE] Improve collection card

### ISSUE THREAD

**Issue by pldnz** [KiranAminPanjwani/LeatherHoard#74]
### 🎇 Description

We could put some effects on hover and create some ctas on cards in collections, what do you think?

### 🖼 Screenshots

![image](https://user-images.githubusercontent.com/23089040/193456522-a4f891f0-9dd3-4c47-acc2-7cbb0a275f9b.png)

**Comment by KiranAminPanjwani** [comment]
Sure, please go ahead! 🤩

**Comment by pldnz** [comment]
could you please accept my pr
