### ISSUE TITLE
Reduce cumulative layout shifts

### ISSUE THREAD

**Issue by pldnz** [KiranAminPanjwani/LeatherHoard#77]
Through pagespeed insights it is possible to see that the site has some CLS, we could improve this by defining width and height for the images.

![image](https://user-images.githubusercontent.com/23089040/193460147-b692b151-6803-4454-84c0-462367d7a9ed.png)

![image](https://user-images.githubusercontent.com/23089040/193460177-c1e60e7a-80cd-444d-90ae-6abfeaf48a89.png)

**Comment by KiranAminPanjwani** [comment]
Ok,ay work on it. I will look at the output and merge it if the output makes the website look appealing. 🤩✨
