### ISSUE TITLE
[FEATURE] Social Media icons redirection 

### ISSUE THREAD

**Issue by akshatjainei** [KiranAminPanjwani/LeatherHoard#78]
### 🎇 Description

Social media icons are not properly managed in different pages also they are dummy button not working so make them redirect towards admins social media handles

**Comment by akshatjainei** [comment]
Can I be assigned for this issue?

**Comment by KiranAminPanjwani** [comment]
Kindly check, if the issue same issue is raised before. Try to find other bugs or add a new feature/section to the website.😊
