### ISSUE TITLE
[FEATURE] : a dedicated About page can be created for the site

### ISSUE THREAD

**Issue by amitanshusahu** [KiranAminPanjwani/LeatherHoard#79]
### when clicked on **Read more** it must redirect to a about page... 
**there can be 2 approaches to make this**
- we could add sections about the project , the admin , the contributors , how to contribute (form contribute.md),..etc.
- or add section about the company , and stuffs .. being in the scope of the site

### 🖼 Screenshots

![image](https://user-images.githubusercontent.com/83657737/193461736-9d5325ad-18f0-49ca-9ce7-f478a0274613.png)

**Comment by amitanshusahu** [comment]
### if assigned to me under hactoberfest , i would like to work on this ..
if the about page is going to be about the project then , about admin , contributors etc can be fetched from the **_github api_** and displayed with  **_real-time data_** , and the contribution.md file can be read with js using  _**FileReader()**_  if possible , it works with input file , but not sure if it can read any href url....

@KiranAminPanjwani  , do share your thoughts on what should be a about page be like ... **_"about the project type"_** or "**_about the company type"_**   😆 😆

**Comment by KiranAminPanjwani** [comment]
I would love it if the "About Us" page would be "About the Company" since this is a website that represents the Leather Hoard Company.😊
