### ISSUE TITLE
Pointer not displaying for the links

### ISSUE THREAD

**Issue by sumitbishti** [KiranAminPanjwani/LeatherHoard#8]
I would like to fix this bug!
![Screenshot (23)](https://user-images.githubusercontent.com/75713174/193058610-86944181-b175-47fe-9d4d-b49dc730e2c2.png)

**Comment by KiranAminPanjwani** [comment]
Please add a screenshot as well.

**Comment by sumitbishti** [comment]
Well i have added, but the cursor is not showing up in the screenshot instead of the cursor it should be hand pointer when hovering the INFO section at the bottom.

**Comment by KiranAminPanjwani** [comment]
> Well i have added, but the cursor is not showing up in the screenshot. Instead of the cursor it should be hand pointer when hovering over the INFO section at the bottom.

Okay, got it! Please go ahead. 🤩

**Comment by sumitbishti** [comment]
Sure

> > Well i have added, but the cursor is not showing up in the screenshot. Instead of the cursor it should be hand pointer when hovering over the INFO section at the bottom.
> 
> Okay, got it! Please go ahead. 🤩
