### ISSUE TITLE
The UI could be enhanced.

### ISSUE THREAD

**Issue by JadugarKalakaboola** [KiranAminPanjwani/LeatherHoard#9]
Hi, nice website overall but in a few places UI can be improved.

1. The boxes are not aligned properly.
![image](https://user-images.githubusercontent.com/90437355/193091066-590a90d1-5b1c-453e-9b87-61b4390df4f1.png)
2. large empty space here.
![image](https://user-images.githubusercontent.com/90437355/193091215-c0679100-d746-4eaa-b9b3-7625412f9971.png)
3. Not centered properly.
![image](https://user-images.githubusercontent.com/90437355/193091478-504b14a4-6af0-4be3-b4b1-da673b470a7e.png)

**Comment by JadugarKalakaboola** [comment]
I would like to work on this project. Please assign this task to me this hacktoberfest :))

**Comment by KiranAminPanjwani** [comment]
Thank you for highlighting this, but I would urge you to look for other bugs if possible.😊
