### ISSUE TITLE
Add scroll to top

### ISSUE THREAD

**Issue by AnshuPathak-88825** [KiranAminPanjwani/LeatherHoard#93]
### 🎇 Description

I want to fixed a button in bottom that take us to top of the webpage 
pls assign me this issue
@KiranAminPanjwani

**Comment by jsapuyesp** [comment]
Can i work in this issue? @KiranAminPanjwani

**Comment by AnshuPathak-88825** [comment]
Bro I've already asked to assign me you can raise another issue @jsapuyesp

**Comment by terrifricker** [comment]
There is not a button to take you back to the top of the webpage, but the logo in the footer links back to the top of the webpage.

**Comment by KiranAminPanjwani** [comment]
@AnshuPathak-88825 Please go ahead. 😊
