### ISSUE TITLE
[FEATURE] Hover effect on section 2 and new arrivals card

### ISSUE THREAD

**Issue by Samaresh-Das** [KiranAminPanjwani/LeatherHoard#95]
### 🎇 Description

Hover effect on section 2 and new arrivals card on home screen. May I work on this under hacktoberfest label?

### 🖼 Screenshots

![Screenshot 2022-10-04 131217](https://user-images.githubusercontent.com/86469290/193762889-30285d56-c3cb-4ca0-a1ab-6e3b6c015e16.png)
![Screenshot 2022-10-04 131239](https://user-images.githubusercontent.com/86469290/193762895-21a0a997-43c0-4b15-bd1f-aec9adb64fa9.png)

**Comment by KiranAminPanjwani** [comment]
Sure! 😊

**Comment by KiranAminPanjwani** [comment]
I really like the animation you have used in the "New Arrivals" section.✨ I will merge your PR.

But the animation in this section👇 is not needed. Please remove it. Thank you.
![image](https://user-images.githubusercontent.com/90326051/194775378-9a063c1c-e3f6-4fd5-b1f9-e959047e9c13.png)

**Comment by Samaresh-Das** [comment]
Ok. I will  do it within tomorrow.😅

**Comment by Samaresh-Das** [comment]
Hello, can you please kindly merge the PR? Thanks. #128

**Comment by Samaresh-Das** [comment]
Hello, there are only some days left in hacktoberfest 2022. Can you please accept the PR?
